### PR TITLE
fix: Add org.junit.jupiter:junit-jupiter-api:5.6.0 dependency

### PR DESCRIPTION
**Pull request by cchacin**

### CODE REVIEW

**Comment by cchacin** [comment]
@t1 This fixes the build for the last @dependabot PR #4

**Comment by t1** [comment]
Many thanks for the contribution!

The problem is that the maven uses the `org.junit.jupiter:junit-jupiter-api:5.5.2` dependency from `org.testcontainers:junit-jupiter` while the `org.junit.jupiter:junit-jupiter:5.6.0` needs `5.6.0`.

Wouldn't it be cleaner to exclude the outdated `org.junit.jupiter:junit-jupiter-api` dependency from `org.testcontainers:junit-jupiter` instead of specifying a new dependency? What do you think?

**Comment by cchacin** [comment]
@t1 Fixed in 72936a4 👍

**Comment by cchacin** [comment]
FYI there are other 6 conflicts in the pom:

image

**Comment by t1** [comment]
LGTM. Many thanks, again!

From what tool is your screenshot?

**Comment by cchacin** [comment]
Maven Helper Plugin: https://plugins.jetbrains.com/plugin/7179-maven-helper/ it's available in the main IntelliJ plugin repository, just search and install it 👍

**Comment by t1** [comment]
The merge didn't work. I puzzled. I did this so many times before, but the change was not in the pom and your name was not in the contributors list. My only explanation is a bug in GitHub.

But I *do* want to have you as a contributor! I can't reopen the PR. Maybe you could create a new one? Sorry for the hassle.

**Comment by cchacin** [comment]
Sent a new PR https://github.com/t1/jee-testcontainers/pull/7

**Pull request merged**
